# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PasswordGenerator.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_PasswordGenerator(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(766, 301)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(45, 219, 436, 20))
        self.horizontalSlider.setCursor(QtGui.QCursor(QtCore.Qt.SplitHCursor))
        self.horizontalSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"background: transparent;\n"
"height: 20px;\n"
"border-radius: 0px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QSlider::handle:horizontal {\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,stop:0 #ffe000,stop:1 #799f0c);\n"
"border: 2px solid #000;\n"
"width: 15px;\n"
"border-radius: 8px;\n"
"}\n"
"\n"
"\n"
"")
        self.horizontalSlider.setInputMethodHints(QtCore.Qt.ImhNone)
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setSingleStep(1)
        self.horizontalSlider.setProperty("value", 1)
        self.horizontalSlider.setTracking(True)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider.setTickInterval(10)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.length = QtWidgets.QLabel(self.centralwidget)
        self.length.setGeometry(QtCore.QRect(480, 213, 61, 31))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.length.setFont(font)
        self.length.setStyleSheet("color: #ffffff;\n"
"border: 2px solid #eeeeee;\n"
"border-radius:10px;\n"
"")
        self.length.setAlignment(QtCore.Qt.AlignCenter)
        self.length.setObjectName("length")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(60, 225, 421, 8))
        self.progressBar.setStyleSheet("QProgressBar\n"
"{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#ffffff, stop:1 #abbaab);\n"
"border: 1px solid #000;\n"
"}\n"
"QProgressBar::chunk \n"
"{\n"
"background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,stop:0 #7f00ff,stop:1 #e100ff);\n"
"\n"
"border: 1px solid #000;\n"
"\n"
"}    ")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 766, 400))
        self.background.setStyleSheet("background:#272822;\n"
"\n"
"")
        self.background.setText("")
        self.background.setObjectName("background")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 120, 436, 18))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("color : #ffffff;\n"
"padding-left: 10;\n"
"background-color: rgb(118, 118, 118);\n"
"background:#272822;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setFrame(False)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.BackgroundBehind_2 = QtWidgets.QLabel(self.centralwidget)
        self.BackgroundBehind_2.setEnabled(True)
        self.BackgroundBehind_2.setGeometry(QtCore.QRect(15, 15, 736, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BackgroundBehind_2.sizePolicy().hasHeightForWidth())
        self.BackgroundBehind_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.BackgroundBehind_2.setFont(font)
        self.BackgroundBehind_2.setToolTipDuration(0)
        self.BackgroundBehind_2.setAutoFillBackground(False)
        self.BackgroundBehind_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#ffffff, stop:1 #abbaab);\n"
"border-radius:5px;\n"
"")
        self.BackgroundBehind_2.setInputMethodHints(QtCore.Qt.ImhNoPredictiveText)
        self.BackgroundBehind_2.setText("")
        self.BackgroundBehind_2.setAlignment(QtCore.Qt.AlignCenter)
        self.BackgroundBehind_2.setObjectName("BackgroundBehind_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(640, 0, 111, 61))
        self.frame.setStyleSheet("background: #00FFFFFF ;\n"
"")
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.help_btn = QtWidgets.QPushButton(self.frame)
        self.help_btn.setMinimumSize(QtCore.QSize(18, 18))
        self.help_btn.setMaximumSize(QtCore.QSize(18, 18))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setBold(True)
        font.setWeight(75)
        self.help_btn.setFont(font)
        self.help_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.help_btn.setStyleSheet("background-color:#272822;\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;")
        self.help_btn.setObjectName("help_btn")
        self.horizontalLayout.addWidget(self.help_btn)
        self.pushButtonMinimize = QtWidgets.QPushButton(self.frame)
        self.pushButtonMinimize.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButtonMinimize.setMaximumSize(QtCore.QSize(18, 18))
        self.pushButtonMinimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonMinimize.setStyleSheet("background-color:#272822;\n"
"border-radius:8px;")
        self.pushButtonMinimize.setText("")
        self.pushButtonMinimize.setObjectName("pushButtonMinimize")
        self.horizontalLayout.addWidget(self.pushButtonMinimize)
        self.pushButtonMaximiz = QtWidgets.QPushButton(self.frame)
        self.pushButtonMaximiz.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButtonMaximiz.setMaximumSize(QtCore.QSize(18, 18))
        self.pushButtonMaximiz.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonMaximiz.setStyleSheet("background-color:#272822;\n"
"\n"
"border-radius:8px;")
        self.pushButtonMaximiz.setText("")
        self.pushButtonMaximiz.setObjectName("pushButtonMaximiz")
        self.horizontalLayout.addWidget(self.pushButtonMaximiz)
        self.pushButtonExit = QtWidgets.QPushButton(self.frame)
        self.pushButtonExit.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButtonExit.setMaximumSize(QtCore.QSize(18, 18))
        self.pushButtonExit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonExit.setStyleSheet("background-color:#272822;\n"
"border-radius:8px;")
        self.pushButtonExit.setText("")
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.horizontalLayout.addWidget(self.pushButtonExit)
        self.progressBar_2 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_2.setGeometry(QtCore.QRect(15, 150, 556, 16))
        self.progressBar_2.setStyleSheet("\n"
"QProgressBar\n"
"{\n"
"border-radius:8px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#ffffff, stop:1 #abbaab);\n"
"\n"
"}\n"
"QProgressBar::chunk \n"
"{\n"
"border-radius:8px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0#FDFC47, stop:1 #24FE41);\n"
"\n"
"}    ")
        self.progressBar_2.setMinimum(1)
        self.progressBar_2.setProperty("value", 1)
        self.progressBar_2.setTextVisible(False)
        self.progressBar_2.setObjectName("progressBar_2")
        self.refresh = QtWidgets.QLabel(self.centralwidget)
        self.refresh.setGeometry(QtCore.QRect(480, 105, 46, 46))
        self.refresh.setStyleSheet("border-right: 2px solid #eeeeee;\n"
"border-left: 2px solid #eeeeee;\n"
"border-top: 2px solid #eeeeee;\n"
"")
        self.refresh.setText("")
        self.refresh.setObjectName("refresh")
        self.refresh_2 = QtWidgets.QLabel(self.centralwidget)
        self.refresh_2.setGeometry(QtCore.QRect(525, 105, 46, 46))
        self.refresh_2.setStyleSheet("")
        self.refresh_2.setText("")
        self.refresh_2.setObjectName("refresh_2")
        self.pushButtonrefresh = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonrefresh.setGeometry(QtCore.QRect(480, 105, 46, 46))
        self.pushButtonrefresh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonrefresh.setStyleSheet("background-color:#00FFFFFF;")
        self.pushButtonrefresh.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("PVS/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonrefresh.setIcon(icon)
        self.pushButtonrefresh.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonrefresh.setObjectName("pushButtonrefresh")
        self.pushButtoncopy = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtoncopy.setGeometry(QtCore.QRect(525, 105, 46, 46))
        self.pushButtoncopy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtoncopy.setStyleSheet("background-color:#00FFFFFF;")
        self.pushButtoncopy.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("PVS/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtoncopy.setIcon(icon1)
        self.pushButtoncopy.setIconSize(QtCore.QSize(30, 30))
        self.pushButtoncopy.setObjectName("pushButtoncopy")
        self.verticalWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget.setGeometry(QtCore.QRect(590, 113, 151, 151))
        self.verticalWidget.setStyleSheet("padding-left: 5;\n"
"\n"
"")
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.symbols_2 = QtWidgets.QCheckBox(self.verticalWidget)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.symbols_2.setFont(font)
        self.symbols_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.symbols_2.setIconSize(QtCore.QSize(20, 16))
        self.symbols_2.setObjectName("symbols_2")
        self.verticalLayout.addWidget(self.symbols_2)
        self.uppercase = QtWidgets.QCheckBox(self.verticalWidget)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.uppercase.setFont(font)
        self.uppercase.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.uppercase.setIconSize(QtCore.QSize(20, 16))
        self.uppercase.setObjectName("uppercase")
        self.verticalLayout.addWidget(self.uppercase)
        self.lowercase = QtWidgets.QCheckBox(self.verticalWidget)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lowercase.setFont(font)
        self.lowercase.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.lowercase.setIconSize(QtCore.QSize(20, 16))
        self.lowercase.setObjectName("lowercase")
        self.verticalLayout.addWidget(self.lowercase)
        self.numbers = QtWidgets.QCheckBox(self.verticalWidget)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.numbers.setFont(font)
        self.numbers.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.numbers.setIconSize(QtCore.QSize(20, 16))
        self.numbers.setObjectName("numbers")
        self.verticalLayout.addWidget(self.numbers)
        self.symbols = QtWidgets.QCheckBox(self.verticalWidget)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.symbols.setFont(font)
        self.symbols.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.symbols.setIconSize(QtCore.QSize(20, 16))
        self.symbols.setObjectName("symbols")
        self.verticalLayout.addWidget(self.symbols)
        self.uppercase.raise_()
        self.lowercase.raise_()
        self.numbers.raise_()
        self.symbols.raise_()
        self.symbols_2.raise_()
        self.bordertick = QtWidgets.QLabel(self.centralwidget)
        self.bordertick.setGeometry(QtCore.QRect(585, 105, 166, 166))
        self.bordertick.setStyleSheet("border: 2px solid #eeeeee;\n"
"border-radius:10px;")
        self.bordertick.setText("")
        self.bordertick.setObjectName("bordertick")
        self.bordertick_2 = QtWidgets.QLabel(self.centralwidget)
        self.bordertick_2.setGeometry(QtCore.QRect(15, 180, 556, 91))
        self.bordertick_2.setStyleSheet("border: 2px solid #eeeeee;\n"
"border-radius:10px;")
        self.bordertick_2.setText("")
        self.bordertick_2.setObjectName("bordertick_2")
        self.refresh_3 = QtWidgets.QLabel(self.centralwidget)
        self.refresh_3.setGeometry(QtCore.QRect(15, 105, 556, 61))
        self.refresh_3.setStyleSheet("border: 2px solid #eeeeee;\n"
"border-radius:10px;")
        self.refresh_3.setText("")
        self.refresh_3.setObjectName("refresh_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(600, 120, 133, 22))
        self.pushButton.setStyleSheet("background: #00FFFFFF ;\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.background.raise_()
        self.refresh_3.raise_()
        self.bordertick.raise_()
        self.bordertick_2.raise_()
        self.BackgroundBehind_2.raise_()
        self.progressBar.raise_()
        self.horizontalSlider.raise_()
        self.lineEdit.raise_()
        self.frame.raise_()
        self.refresh.raise_()
        self.refresh_2.raise_()
        self.pushButtonrefresh.raise_()
        self.pushButtoncopy.raise_()
        self.length.raise_()
        self.progressBar_2.raise_()
        self.pushButton.raise_()
        self.verticalWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.horizontalSlider.sliderMoved['int'].connect(self.length.setNum) # type: ignore
        self.horizontalSlider.sliderMoved['int'].connect(self.progressBar.setValue) # type: ignore
        self.horizontalSlider.sliderMoved['int'].connect(self.progressBar_2.setValue) # type: ignore
        self.symbols_2.clicked.connect(self.pushButton.click) # type: ignore
        self.pushButtonExit.clicked.connect(MainWindow.close) # type: ignore
        self.pushButtonMinimize.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.length.setText(_translate("MainWindow", "0"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Your Password"))
        self.help_btn.setText(_translate("MainWindow", "H"))
        self.symbols_2.setText(_translate("MainWindow", "All"))
        self.uppercase.setText(_translate("MainWindow", "Uppercase"))
        self.lowercase.setText(_translate("MainWindow", "Lowercase"))
        self.numbers.setText(_translate("MainWindow", "Numbers"))
        self.symbols.setText(_translate("MainWindow", "Symbols"))


